In [3]:
%pip install pandas

Collecting pandas
  Using cached pandas-3.0.0-cp311-cp311-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\users\yashs\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\yashs\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Using cached tzdata-2025.3-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\yashs\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.0-cp311-cp311-win_amd64.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.9 MB 335.7 kB/s eta 0:00:28
   -- ------------------------------------- 0.5/9.9 MB 335.7 kB/s eta 0:00:28
   -- ------------------------------------- 0.5/9.9 MB 335.7 kB/s eta 0:00:28
   --- ------------------------------------ 0.8/9.9 MB 335.7 kB/s eta 0:00:28
   --- ------------------------------------ 0.8/9.9 MB 335.7 kB/s eta 0:00:28
   --- ------------------------------------ 0.8/9.9 MB 335.7 kB/s eta 0:00:28
   ---- ----------------------------------- 1.0/9.9 MB 333.4 kB/s eta 0:00:27
   ---- ----------------------------------- 1.0/9.9 MB 333.4 kB/s eta 0:00:27
   ---- ----------------------------------- 1.0/9.9 MB 333.4 kB/s eta 0:00:27
   ----- ---------------------------------- 1.3/9.9 MB 301.0 kB/s eta 0:00:29
   ----- ---------------------------------- 1.3/9.9 MB 301.0 kB/s eta 0:00:29
   ----- ---------------------------------- 1.3/9.9 MB 301.0 kB/s eta 0:00:29
   ------ --------------------------------- 1.6/9.9 MB 309.6 kB/s eta 0:00:27
   ------ --------------------------------- 1.6/9.9 MB 309.6 kB/s eta 0:00:27
   ------ --------------------------------- 1.6/9.9 MB 309.6 kB/s eta 0:00:27
   ------ --------------------------------- 1.6/9.9 MB 309.6 kB/s eta 0:00:27
   ------- -------------------------------- 1.8/9.9 MB 269.1 kB/s eta 0:00:30
   ------- -------------------------------- 1.8/9.9 MB 269.1 kB/s eta 0:00:30
   ------- -------------------------------- 1.8/9.9 MB 269.1 kB/s eta 0:00:30
   ------- -------------------------------- 1.8/9.9 MB 269.1 kB/s eta 0:00:30
   -------- ------------------------------- 2.1/9.9 MB 254.2 kB/s eta 0:00:31
   -------- ------------------------------- 2.1/9.9 MB 254.2 kB/s eta 0:00:31
   -------- ------------------------------- 2.1/9.9 MB 254.2 kB/s eta 0:00:31
   -------- ------------------------------- 2.1/9.9 MB 254.2 kB/s eta 0:00:31
   -------- ------------------------------- 2.1/9.9 MB 254.2 kB/s eta 0:00:31
   --------- ------------------------------ 2.4/9.9 MB 252.3 kB/s eta 0:00:30
   --------- ------------------------------ 2.4/9.9 MB 252.3 kB/s eta 0:00:30
   --------- ------------------------------ 2.4/9.9 MB 252.3 kB/s eta 0:00:30
   --------- ------------------------------ 2.4/9.9 MB 252.3 kB/s eta 0:00:30
   --------- ------------------------------ 2.4/9.9 MB 252.3 kB/s eta 0:00:30
   ---------- ----------------------------- 2.6/9.9 MB 237.0 kB/s eta 0:00:31
   ---------- ----------------------------- 2.6/9.9 MB 237.0 kB/s eta 0:00:31
   ---------- ----------------------------- 2.6/9.9 MB 237.0 kB/s eta 0:00:31
   ---------- ----------------------------- 2.6/9.9 MB 237.0 kB/s eta 0:00:31
   ---------- ----------------------------- 2.6/9.9 MB 237.0 kB/s eta 0:00:31
   ---------- ----------------------------- 2.6/9.9 MB 237.0 kB/s eta 0:00:31
   ---------- ----------------------------- 2.6/9.9 MB 237.0 kB/s eta 0:00:31
   ---------- ----------------------------- 2.6/9.9 MB 237.0 kB/s eta 0:00:31
   ---------- ----------------------------- 2.6/9.9 MB 237.0 kB/s eta 0:00:31
   ---------- ----------------------------- 2.6/9.9 MB 237.0 kB/s eta 0:00:31
   ----------- ---------------------------- 2.9/9.9 MB 213.5 kB/s eta 0:00:33
   ----------- ---------------------------- 2.9/9.9 MB 213.5 kB/s eta 0:00:33
   ----------- ---------------------------- 2.9/9.9 MB 213.5 kB/s eta 0:00:33
   ----------- ---------------------------- 2.9/9.9 MB 213.5 kB/s eta 0:00:33
   ----------- ---------------------------- 2.9/9.9 MB 213.5 kB/s eta 0:00:33
   ----------- ---------------------------- 2.9/9.9 MB 213.5 kB/s eta 0:00:33
   ------------ --------------------------- 3.1/9.9 MB 214.8 kB/s eta 0:00:32
   ------------ --------------------------- 3.1/9.9 MB 214.8 kB/s eta 0:00:32
   ------------ --------------------------- 3.1/9.9 MB 214.8 kB/s eta 0:00:32
   ------------ --------------------------- 3.1/9.9 MB 214.8 kB/s eta 0:00:32
   ------------ --------------------------- 3.1/9.9 MB 214.8 kB/s eta 0:00:32
   ------------- -------------------------- 3.4/9.9 MB 216.5 kB/s eta 0:00:30
   ------------- -------------------------- 3.4/9.9 MB 216.5 kB/s eta 0:00:30
   ------------- -------------------------- 3.4/9.9 MB 216.5 kB/s eta 0:00:30
   ------------- -------------------------- 3.4/9.9 MB 216.5 kB/s eta 0:00:30
   -------------- ------------------------- 3.7/9.9 MB 219.9 kB/s eta 0:00:29
   -------------- ------------------------- 3.7/9.9 MB 219.9 kB/s eta 0:00:29
   -------------- ------------------------- 3.7/9.9 MB 219.9 kB/s eta 0:00:29
   -------------- ------------------------- 3.7/9.9 MB 219.9 kB/s eta 0:00:29
   -------------- ------------------------- 3.7/9.9 MB 219.9 kB/s eta 0:00:29
   -------------- ------------------------- 3.7/9.9 MB 219.9 kB/s eta 0:00:29
   --------------- ------------------------ 3.9/9.9 MB 220.5 kB/s eta 0:00:27
   --------------- ------------------------ 3.9/9.9 MB 220.5 kB/s eta 0:00:27
   --------------- ------------------------ 3.9/9.9 MB 220.5 kB/s eta 0:00:27
   --------------- ------------------------ 3.9/9.9 MB 220.5 kB/s eta 0:00:27
   --------------- ------------------------ 3.9/9.9 MB 220.5 kB/s eta 0:00:27
   --------------- ------------------------ 3.9/9.9 MB 220.5 kB/s eta 0:00:27
   --------------- ------------------------ 3.9/9.9 MB 220.5 kB/s eta 0:00:27
   ---------------- ----------------------- 4.2/9.9 MB 215.8 kB/s eta 0:00:27
   ---------------- ----------------------- 4.2/9.9 MB 215.8 kB/s eta 0:00:27
   ---------------- ----------------------- 4.2/9.9 MB 215.8 kB/s eta 0:00:27
   ---------------- ----------------------- 4.2/9.9 MB 215.8 kB/s eta 0:00:27
   ---------------- ----------------------- 4.2/9.9 MB 215.8 kB/s eta 0:00:27
   ------------------ --------------------- 4.5/9.9 MB 206.8 kB/s eta 0:00:27
   ------------------ --------------------- 4.5/9.9 MB 206.8 kB/s eta 0:00:27
   ------------------ --------------------- 4.5/9.9 MB 206.8 kB/s eta 0:00:27
   ------------------ --------------------- 4.5/9.9 MB 206.8 kB/s eta 0:00:27
   ------------------ --------------------- 4.5/9.9 MB 206.8 kB/s eta 0:00:27
   ------------------ --------------------- 4.5/9.9 MB 206.8 kB/s eta 0:00:27
   ------------------ --------------------- 4.5/9.9 MB 206.8 kB/s eta 0:00:27
   ------------------- -------------------- 4.7/9.9 MB 203.9 kB/s eta 0:00:26
   ------------------- -------------------- 4.7/9.9 MB 203.9 kB/s eta 0:00:26
   ------------------- -------------------- 4.7/9.9 MB 203.9 kB/s eta 0:00:26
   ------------------- -------------------- 4.7/9.9 MB 203.9 kB/s eta 0:00:26
   ------------------- -------------------- 4.7/9.9 MB 203.9 kB/s eta 0:00:26
   ------------------- -------------------- 4.7/9.9 MB 203.9 kB/s eta 0:00:26
   ------------------- -------------------- 4.7/9.9 MB 203.9 kB/s eta 0:00:26
   ------------------- -------------------- 4.7/9.9 MB 203.9 kB/s eta 0:00:26
   ------------------- -------------------- 4.7/9.9 MB 203.9 kB/s eta 0:00:26
   -------------------- ------------------- 5.0/9.9 MB 197.1 kB/s eta 0:00:25
   -------------------- ------------------- 5.0/9.9 MB 197.1 kB/s eta 0:00:25
   -------------------- ------------------- 5.0/9.9 MB 197.1 kB/s eta 0:00:25
   -------------------- ------------------- 5.0/9.9 MB 197.1 kB/s eta 0:00:25
   -------------------- ------------------- 5.0/9.9 MB 197.1 kB/s eta 0:00:25
   -------------------- ------------------- 5.0/9.9 MB 197.1 kB/s eta 0:00:25
   -------------------- ------------------- 5.0/9.9 MB 197.1 kB/s eta 0:00:25
   --------------------- ------------------ 5.2/9.9 MB 195.1 kB/s eta 0:00:24
   --------------------- ------------------ 5.2/9.9 MB 195.1 kB/s eta 0:00:24
   --------------------- ------------------ 5.2/9.9 MB 195.1 kB/s eta 0:00:24
   --------------------- ------------------ 5.2/9.9 MB 195.1 kB/s eta 0:00:24
   --------------------- ------------------ 5.2/9.9 MB 195.1 kB/s eta 0:00:24
   ---------------------- ----------------- 5.5/9.9 MB 198.2 kB/s eta 0:00:23
   ---------------------- ----------------- 5.5/9.9 MB 198.2 kB/s eta 0:00:23
   ---------------------- ----------------- 5.5/9.9 MB 198.2 kB/s eta 0:00:23
   ---------------------- ----------------- 5.5/9.9 MB 198.2 kB/s eta 0:00:23
   ---------------------- ----------------- 5.5/9.9 MB 198.2 kB/s eta 0:00:23
   ---------------------- ----------------- 5.5/9.9 MB 198.2 kB/s eta 0:00:23
   ---------------------- ----------------- 5.5/9.9 MB 198.2 kB/s eta 0:00:23
   ---------------------- ----------------- 5.5/9.9 MB 198.2 kB/s eta 0:00:23
   ---------------------- ----------------- 5.5/9.9 MB 198.2 kB/s eta 0:00:23
   ---------------------- ----------------- 5.5/9.9 MB 198.2 kB/s eta 0:00:23
   ----------------------- ---------------- 5.8/9.9 MB 192.8 kB/s eta 0:00:22
   ----------------------- ---------------- 5.8/9.9 MB 192.8 kB/s eta 0:00:22
   ----------------------- ---------------- 5.8/9.9 MB 192.8 kB/s eta 0:00:22
   ----------------------- ---------------- 5.8/9.9 MB 192.8 kB/s eta 0:00:22
   ----------------------- ---------------- 5.8/9.9 MB 192.8 kB/s eta 0:00:22
   ----------------------- ---------------- 5.8/9.9 MB 192.8 kB/s eta 0:00:22
   ----------------------- ---------------- 5.8/9.9 MB 192.8 kB/s eta 0:00:22
   ------------------------ --------------- 6.0/9.9 MB 187.6 kB/s eta 0:00:21
   ------------------------ --------------- 6.0/9.9 MB 187.6 kB/s eta 0:00:21
   ------------------------ --------------- 6.0/9.9 MB 187.6 kB/s eta 0:00:21
   ------------------------ --------------- 6.0/9.9 MB 187.6 kB/s eta 0:00:21
   ------------------------ --------------- 6.0/9.9 MB 187.6 kB/s eta 0:00:21
   ------------------------ --------------- 6.0/9.9 MB 187.6 kB/s eta 0:00:21
   ------------------------ --------------- 6.0/9.9 MB 187.6 kB/s eta 0:00:21
   ------------------------- -------------- 6.3/9.9 MB 183.8 kB/s eta 0:00:20
   ------------------------- -------------- 6.3/9.9 MB 183.8 kB/s eta 0:00:20
   ------------------------- -------------- 6.3/9.9 MB 183.8 kB/s eta 0:00:20
   ------------------------- -------------- 6.3/9.9 MB 183.8 kB/s eta 0:00:20
   -------------------------- ------------- 6.6/9.9 MB 180.9 kB/s eta 0:00:19
   -------------------------- ------------- 6.6/9.9 MB 180.9 kB/s eta 0:00:19
   -------------------------- ------------- 6.6/9.9 MB 180.9 kB/s eta 0:00:19
   -------------------------- ------------- 6.6/9.9 MB 180.9 kB/s eta 0:00:19
   -------------------------- ------------- 6.6/9.9 MB 180.9 kB/s eta 0:00:19
   --------------------------- ------------ 6.8/9.9 MB 178.6 kB/s eta 0:00:18
   --------------------------- ------------ 6.8/9.9 MB 178.6 kB/s eta 0:00:18
   --------------------------- ------------ 6.8/9.9 MB 178.6 kB/s eta 0:00:18
   --------------------------- ------------ 6.8/9.9 MB 178.6 kB/s eta 0:00:18
   --------------------------- ------------ 6.8/9.9 MB 178.6 kB/s eta 0:00:18
   ---------------------------- ----------- 7.1/9.9 MB 182.4 kB/s eta 0:00:16
   ---------------------------- ----------- 7.1/9.9 MB 182.4 kB/s eta 0:00:16
   ---------------------------- ----------- 7.1/9.9 MB 182.4 kB/s eta 0:00:16
   ---------------------------- ----------- 7.1/9.9 MB 182.4 kB/s eta 0:00:16
   ----------------------------- ---------- 7.3/9.9 MB 187.0 kB/s eta 0:00:14
   ----------------------------- ---------- 7.3/9.9 MB 187.0 kB/s eta 0:00:14
   ------------------------------ --------- 7.6/9.9 MB 192.5 kB/s eta 0:00:12
   ------------------------------ --------- 7.6/9.9 MB 192.5 kB/s eta 0:00:12
   ------------------------------- -------- 7.9/9.9 MB 198.9 kB/s eta 0:00:11
   ------------------------------- -------- 7.9/9.9 MB 198.9 kB/s eta 0:00:11
   -------------------------------- ------- 8.1/9.9 MB 204.4 kB/s eta 0:00:09
   -------------------------------- ------- 8.1/9.9 MB 204.4 kB/s eta 0:00:09
   -------------------------------- ------- 8.1/9.9 MB 204.4 kB/s eta 0:00:09
   --------------------------------- ------ 8.4/9.9 MB 210.2 kB/s eta 0:00:08
   ----------------------------------- ---- 8.7/9.9 MB 215.5 kB/s eta 0:00:06
   ------------------------------------ --- 8.9/9.9 MB 221.6 kB/s eta 0:00:05
   ------------------------------------ --- 8.9/9.9 MB 221.6 kB/s eta 0:00:05
   ------------------------------------- -- 9.2/9.9 MB 228.3 kB/s eta 0:00:04
   ---------------------------------------  9.7/9.9 MB 245.8 kB/s eta 0:00:01
   ---------------------------------------  9.7/9.9 MB 245.8 kB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 247.7 kB/s  0:00:39
Using cached tzdata-2025.3-py2.py3-none-any.whl (348 kB)
Installing collected packages: tzdata, pandas

   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]

Note: you may need to restart the kernel to use updated packages.

ERROR: Could not install packages due to an OSError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\yashs\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\pandas\\tests\\arrays\\categorical\\test_map.py'
Check the permissions.

Collecting pandas
  Downloading pandas-3.0.0-cp311-cp311-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\users\yashs\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\yashs\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Using cached tzdata-2025.3-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\yashs\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.0-cp311-cp311-win_amd64.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.9 MB 47.4 kB/s eta 0:03:18
   -- ------------------------------------- 0.5/9.9 MB 47.4 kB/s eta 0:03:18
   -- ------------------------------------- 0.5/9.9 MB 47.4 kB/s eta 0:03:18
   -- ------------------------------------- 0.5/9.9 MB 47.4 kB/s eta 0:03:18
   -- ------------------------------------- 0.5/9.9 MB 47.4 kB/s eta 0:03:18
   -- ------------------------------------- 0.5/9.9 MB 47.4 kB/s eta 0:03:18
   -- ------------------------------------- 0.5/9.9 MB 47.4 kB/s eta 0:03:18
   -- ------------------------------------- 0.5/9.9 MB 47.4 kB/s eta 0:03:18
   -- ------------------------------------- 0.5/9.9 MB 47.4 kB/s eta 0:03:18
   -- ------------------------------------- 0.5/9.9 MB 47.4 kB/s eta 0:03:18
   -- ------------------------------------- 0.5/9.9 MB 47.4 kB/s eta 0:03:18
   -- ------------------------------------- 0.5/9.9 MB 47.4 kB/s eta 0:03:18
   -- ------------------------------------- 0.5/9.9 MB 47.4 kB/s eta 0:03:18
   -- ------------------------------------- 0.5/9.9 MB 47.4 kB/s eta 0:03:18
   -- ------------------------------------- 0.5/9.9 MB 47.4 kB/s eta 0:03:18
   -- ------------------------------------- 0.5/9.9 MB 47.4 kB/s eta 0:03:18
   -- ------------------------------------- 0.5/9.9 MB 47.4 kB/s eta 0:03:18
   -- ------------------------------------- 0.5/9.9 MB 47.4 kB/s eta 0:03:18
   -- ------------------------------------- 0.5/9.9 MB 47.4 kB/s eta 0:03:18
   -- ------------------------------------- 0.5/9.9 MB 47.4 kB/s eta 0:03:18
   -- ------------------------------------- 0.5/9.9 MB 47.4 kB/s eta 0:03:18
   -- ------------------------------------- 0.5/9.9 MB 47.4 kB/s eta 0:03:18
   -- ------------------------------------- 0.5/9.9 MB 47.4 kB/s eta 0:03:18
   --- ------------------------------------ 0.8/9.9 MB 50.5 kB/s eta 0:03:00
   --- ------------------------------------ 0.8/9.9 MB 50.5 kB/s eta 0:03:00
   --- ------------------------------------ 0.8/9.9 MB 50.5 kB/s eta 0:03:00
   --- ------------------------------------ 0.8/9.9 MB 50.5 kB/s eta 0:03:00
   --- ------------------------------------ 0.8/9.9 MB 50.5 kB/s eta 0:03:00
   --- ------------------------------------ 0.8/9.9 MB 50.5 kB/s eta 0:03:00
   --- ------------------------------------ 0.8/9.9 MB 50.5 kB/s eta 0:03:00
   --- ------------------------------------ 0.8/9.9 MB 50.5 kB/s eta 0:03:00
   ---- ----------------------------------- 1.0/9.9 MB 64.8 kB/s eta 0:02:17
   ---- ----------------------------------- 1.0/9.9 MB 64.8 kB/s eta 0:02:17
   ---- ----------------------------------- 1.0/9.9 MB 64.8 kB/s eta 0:02:17
   ---- ----------------------------------- 1.0/9.9 MB 64.8 kB/s eta 0:02:17
   ---- ----------------------------------- 1.0/9.9 MB 64.8 kB/s eta 0:02:17
   ----- ---------------------------------- 1.3/9.9 MB 79.8 kB/s eta 0:01:48
   ----- ---------------------------------- 1.3/9.9 MB 79.8 kB/s eta 0:01:48
   ----- ---------------------------------- 1.3/9.9 MB 79.8 kB/s eta 0:01:48
   ------ --------------------------------- 1.6/9.9 MB 95.2 kB/s eta 0:01:28
   ------ --------------------------------- 1.6/9.9 MB 95.2 kB/s eta 0:01:28
   ------ --------------------------------- 1.6/9.9 MB 95.2 kB/s eta 0:01:28
   ------- -------------------------------- 1.8/9.9 MB 109.2 kB/s eta 0:01:14
   ------- -------------------------------- 1.8/9.9 MB 109.2 kB/s eta 0:01:14
   ------- -------------------------------- 1.8/9.9 MB 109.2 kB/s eta 0:01:14
   ------- -------------------------------- 1.8/9.9 MB 109.2 kB/s eta 0:01:14
   ------- -------------------------------- 1.8/9.9 MB 109.2 kB/s eta 0:01:14
   -------- ------------------------------- 2.1/9.9 MB 117.8 kB/s eta 0:01:07
   -------- ------------------------------- 2.1/9.9 MB 117.8 kB/s eta 0:01:07
   -------- ------------------------------- 2.1/9.9 MB 117.8 kB/s eta 0:01:07
   -------- ------------------------------- 2.1/9.9 MB 117.8 kB/s eta 0:01:07
   --------- ------------------------------ 2.4/9.9 MB 128.7 kB/s eta 0:00:59
   --------- ------------------------------ 2.4/9.9 MB 128.7 kB/s eta 0:00:59
   --------- ------------------------------ 2.4/9.9 MB 128.7 kB/s eta 0:00:59
   --------- ------------------------------ 2.4/9.9 MB 128.7 kB/s eta 0:00:59
   --------- ------------------------------ 2.4/9.9 MB 128.7 kB/s eta 0:00:59
   ---------- ----------------------------- 2.6/9.9 MB 136.0 kB/s eta 0:00:54
   ---------- ----------------------------- 2.6/9.9 MB 136.0 kB/s eta 0:00:54
   ---------- ----------------------------- 2.6/9.9 MB 136.0 kB/s eta 0:00:54
   ---------- ----------------------------- 2.6/9.9 MB 136.0 kB/s eta 0:00:54
   ---------- ----------------------------- 2.6/9.9 MB 136.0 kB/s eta 0:00:54
   ----------- ---------------------------- 2.9/9.9 MB 142.4 kB/s eta 0:00:50
   ----------- ---------------------------- 2.9/9.9 MB 142.4 kB/s eta 0:00:50
   ----------- ---------------------------- 2.9/9.9 MB 142.4 kB/s eta 0:00:50
   ----------- ---------------------------- 2.9/9.9 MB 142.4 kB/s eta 0:00:50
   ------------ --------------------------- 3.1/9.9 MB 149.6 kB/s eta 0:00:46
   ------------ --------------------------- 3.1/9.9 MB 149.6 kB/s eta 0:00:46
   ------------ --------------------------- 3.1/9.9 MB 149.6 kB/s eta 0:00:46
   ------------ --------------------------- 3.1/9.9 MB 149.6 kB/s eta 0:00:46
   ------------ --------------------------- 3.1/9.9 MB 149.6 kB/s eta 0:00:46
   ------------ --------------------------- 3.1/9.9 MB 149.6 kB/s eta 0:00:46
   ------------ --------------------------- 3.1/9.9 MB 149.6 kB/s eta 0:00:46
   ------------ --------------------------- 3.1/9.9 MB 149.6 kB/s eta 0:00:46
   ------------ --------------------------- 3.1/9.9 MB 149.6 kB/s eta 0:00:46
   ------------ --------------------------- 3.1/9.9 MB 149.6 kB/s eta 0:00:46
   ------------- -------------------------- 3.4/9.9 MB 147.1 kB/s eta 0:00:45
   ------------- -------------------------- 3.4/9.9 MB 147.1 kB/s eta 0:00:45
   ------------- -------------------------- 3.4/9.9 MB 147.1 kB/s eta 0:00:45
   ------------- -------------------------- 3.4/9.9 MB 147.1 kB/s eta 0:00:45
   ------------- -------------------------- 3.4/9.9 MB 147.1 kB/s eta 0:00:45
   ------------- -------------------------- 3.4/9.9 MB 147.1 kB/s eta 0:00:45
   ------------- -------------------------- 3.4/9.9 MB 147.1 kB/s eta 0:00:45
   ------------- -------------------------- 3.4/9.9 MB 147.1 kB/s eta 0:00:45
   ------------- -------------------------- 3.4/9.9 MB 147.1 kB/s eta 0:00:45
   -------------- ------------------------- 3.7/9.9 MB 145.5 kB/s eta 0:00:43
   -------------- ------------------------- 3.7/9.9 MB 145.5 kB/s eta 0:00:43
   -------------- ------------------------- 3.7/9.9 MB 145.5 kB/s eta 0:00:43
   -------------- ------------------------- 3.7/9.9 MB 145.5 kB/s eta 0:00:43
   -------------- ------------------------- 3.7/9.9 MB 145.5 kB/s eta 0:00:43
   -------------- ------------------------- 3.7/9.9 MB 145.5 kB/s eta 0:00:43
   -------------- ------------------------- 3.7/9.9 MB 145.5 kB/s eta 0:00:43
   --------------- ------------------------ 3.9/9.9 MB 147.4 kB/s eta 0:00:41
   --------------- ------------------------ 3.9/9.9 MB 147.4 kB/s eta 0:00:41
   --------------- ------------------------ 3.9/9.9 MB 147.4 kB/s eta 0:00:41
   --------------- ------------------------ 3.9/9.9 MB 147.4 kB/s eta 0:00:41
   ---------------- ----------------------- 4.2/9.9 MB 153.4 kB/s eta 0:00:38
   ---------------- ----------------------- 4.2/9.9 MB 153.4 kB/s eta 0:00:38
   ---------------- ----------------------- 4.2/9.9 MB 153.4 kB/s eta 0:00:38
   ---------------- ----------------------- 4.2/9.9 MB 153.4 kB/s eta 0:00:38
   ---------------- ----------------------- 4.2/9.9 MB 153.4 kB/s eta 0:00:38
   ---------------- ----------------------- 4.2/9.9 MB 153.4 kB/s eta 0:00:38
   ---------------- ----------------------- 4.2/9.9 MB 153.4 kB/s eta 0:00:38
   ---------------- ----------------------- 4.2/9.9 MB 153.4 kB/s eta 0:00:38
   ------------------ --------------------- 4.5/9.9 MB 153.7 kB/s eta 0:00:36
   ------------------ --------------------- 4.5/9.9 MB 153.7 kB/s eta 0:00:36
   ------------------ --------------------- 4.5/9.9 MB 153.7 kB/s eta 0:00:36
   ------------------ --------------------- 4.5/9.9 MB 153.7 kB/s eta 0:00:36
   ------------------ --------------------- 4.5/9.9 MB 153.7 kB/s eta 0:00:36
   ------------------ --------------------- 4.5/9.9 MB 153.7 kB/s eta 0:00:36
   ------------------ --------------------- 4.5/9.9 MB 153.7 kB/s eta 0:00:36
   ------------------ --------------------- 4.5/9.9 MB 153.7 kB/s eta 0:00:36
   ------------------ --------------------- 4.5/9.9 MB 153.7 kB/s eta 0:00:36
   ------------------ --------------------- 4.5/9.9 MB 153.7 kB/s eta 0:00:36
   ------------------ --------------------- 4.5/9.9 MB 153.7 kB/s eta 0:00:36
   ------------------ --------------------- 4.5/9.9 MB 153.7 kB/s eta 0:00:36
   ------------------- -------------------- 4.7/9.9 MB 149.8 kB/s eta 0:00:35
   ------------------- -------------------- 4.7/9.9 MB 149.8 kB/s eta 0:00:35
   ------------------- -------------------- 4.7/9.9 MB 149.8 kB/s eta 0:00:35
   ------------------- -------------------- 4.7/9.9 MB 149.8 kB/s eta 0:00:35
   ------------------- -------------------- 4.7/9.9 MB 149.8 kB/s eta 0:00:35
   ------------------- -------------------- 4.7/9.9 MB 149.8 kB/s eta 0:00:35
   -------------------- ------------------- 5.0/9.9 MB 173.8 kB/s eta 0:00:29
   -------------------- ------------------- 5.0/9.9 MB 173.8 kB/s eta 0:00:29
   -------------------- ------------------- 5.0/9.9 MB 173.8 kB/s eta 0:00:29
   -------------------- ------------------- 5.0/9.9 MB 173.8 kB/s eta 0:00:29
   -------------------- ------------------- 5.0/9.9 MB 173.8 kB/s eta 0:00:29
   -------------------- ------------------- 5.0/9.9 MB 173.8 kB/s eta 0:00:29
   --------------------- ------------------ 5.2/9.9 MB 176.2 kB/s eta 0:00:27
   --------------------- ------------------ 5.2/9.9 MB 176.2 kB/s eta 0:00:27
   --------------------- ------------------ 5.2/9.9 MB 176.2 kB/s eta 0:00:27
   --------------------- ------------------ 5.2/9.9 MB 176.2 kB/s eta 0:00:27
   --------------------- ------------------ 5.2/9.9 MB 176.2 kB/s eta 0:00:27
   ---------------------- ----------------- 5.5/9.9 MB 175.5 kB/s eta 0:00:25
   ---------------------- ----------------- 5.5/9.9 MB 175.5 kB/s eta 0:00:25
   ---------------------- ----------------- 5.5/9.9 MB 175.5 kB/s eta 0:00:25
   ---------------------- ----------------- 5.5/9.9 MB 175.5 kB/s eta 0:00:25
   ---------------------- ----------------- 5.5/9.9 MB 175.5 kB/s eta 0:00:25
   ----------------------- ---------------- 5.8/9.9 MB 177.6 kB/s eta 0:00:24
   ----------------------- ---------------- 5.8/9.9 MB 177.6 kB/s eta 0:00:24
   ----------------------- ---------------- 5.8/9.9 MB 177.6 kB/s eta 0:00:24
   ----------------------- ---------------- 5.8/9.9 MB 177.6 kB/s eta 0:00:24
   ----------------------- ---------------- 5.8/9.9 MB 177.6 kB/s eta 0:00:24
   ----------------------- ---------------- 5.8/9.9 MB 177.6 kB/s eta 0:00:24
   ----------------------- ---------------- 5.8/9.9 MB 177.6 kB/s eta 0:00:24
   ------------------------ --------------- 6.0/9.9 MB 199.3 kB/s eta 0:00:20
   ------------------------ --------------- 6.0/9.9 MB 199.3 kB/s eta 0:00:20
   ------------------------ --------------- 6.0/9.9 MB 199.3 kB/s eta 0:00:20
   ------------------------ --------------- 6.0/9.9 MB 199.3 kB/s eta 0:00:20
   ------------------------ --------------- 6.0/9.9 MB 199.3 kB/s eta 0:00:20
   ------------------------ --------------- 6.0/9.9 MB 199.3 kB/s eta 0:00:20
   ------------------------- -------------- 6.3/9.9 MB 195.3 kB/s eta 0:00:19
   ------------------------- -------------- 6.3/9.9 MB 195.3 kB/s eta 0:00:19
   ------------------------- -------------- 6.3/9.9 MB 195.3 kB/s eta 0:00:19
   ------------------------- -------------- 6.3/9.9 MB 195.3 kB/s eta 0:00:19
   ------------------------- -------------- 6.3/9.9 MB 195.3 kB/s eta 0:00:19
   -------------------------- ------------- 6.6/9.9 MB 195.2 kB/s eta 0:00:18
   -------------------------- ------------- 6.6/9.9 MB 195.2 kB/s eta 0:00:18
   -------------------------- ------------- 6.6/9.9 MB 195.2 kB/s eta 0:00:18
   -------------------------- ------------- 6.6/9.9 MB 195.2 kB/s eta 0:00:18
   --------------------------- ------------ 6.8/9.9 MB 195.1 kB/s eta 0:00:16
   --------------------------- ------------ 6.8/9.9 MB 195.1 kB/s eta 0:00:16
   --------------------------- ------------ 6.8/9.9 MB 195.1 kB/s eta 0:00:16
   --------------------------- ------------ 6.8/9.9 MB 195.1 kB/s eta 0:00:16
   --------------------------- ------------ 6.8/9.9 MB 195.1 kB/s eta 0:00:16
   --------------------------- ------------ 6.8/9.9 MB 195.1 kB/s eta 0:00:16
   ---------------------------- ----------- 7.1/9.9 MB 192.7 kB/s eta 0:00:15
   ---------------------------- ----------- 7.1/9.9 MB 192.7 kB/s eta 0:00:15
   ---------------------------- ----------- 7.1/9.9 MB 192.7 kB/s eta 0:00:15
   ---------------------------- ----------- 7.1/9.9 MB 192.7 kB/s eta 0:00:15
   ---------------------------- ----------- 7.1/9.9 MB 192.7 kB/s eta 0:00:15
   ---------------------------- ----------- 7.1/9.9 MB 192.7 kB/s eta 0:00:15
   ---------------------------- ----------- 7.1/9.9 MB 192.7 kB/s eta 0:00:15
   ---------------------------- ----------- 7.1/9.9 MB 192.7 kB/s eta 0:00:15
   ---------------------------- ----------- 7.1/9.9 MB 192.7 kB/s eta 0:00:15
   ----------------------------- ---------- 7.3/9.9 MB 177.2 kB/s eta 0:00:15
   ----------------------------- ---------- 7.3/9.9 MB 177.2 kB/s eta 0:00:15
   ----------------------------- ---------- 7.3/9.9 MB 177.2 kB/s eta 0:00:15
   ----------------------------- ---------- 7.3/9.9 MB 177.2 kB/s eta 0:00:15
   ----------------------------- ---------- 7.3/9.9 MB 177.2 kB/s eta 0:00:15
   ----------------------------- ---------- 7.3/9.9 MB 177.2 kB/s eta 0:00:15
   ------------------------------ --------- 7.6/9.9 MB 169.6 kB/s eta 0:00:14
   ------------------------------ --------- 7.6/9.9 MB 169.6 kB/s eta 0:00:14
   ------------------------------ --------- 7.6/9.9 MB 169.6 kB/s eta 0:00:14
   ------------------------------ --------- 7.6/9.9 MB 169.6 kB/s eta 0:00:14
   ------------------------------- -------- 7.9/9.9 MB 169.1 kB/s eta 0:00:12
   ------------------------------- -------- 7.9/9.9 MB 169.1 kB/s eta 0:00:12
   ------------------------------- -------- 7.9/9.9 MB 169.1 kB/s eta 0:00:12
   -------------------------------- ------- 8.1/9.9 MB 169.0 kB/s eta 0:00:11
   -------------------------------- ------- 8.1/9.9 MB 169.0 kB/s eta 0:00:11
   -------------------------------- ------- 8.1/9.9 MB 169.0 kB/s eta 0:00:11
   -------------------------------- ------- 8.1/9.9 MB 169.0 kB/s eta 0:00:11
   --------------------------------- ------ 8.4/9.9 MB 172.0 kB/s eta 0:00:09
   --------------------------------- ------ 8.4/9.9 MB 172.0 kB/s eta 0:00:09
   --------------------------------- ------ 8.4/9.9 MB 172.0 kB/s eta 0:00:09
   --------------------------------- ------ 8.4/9.9 MB 172.0 kB/s eta 0:00:09
   ----------------------------------- ---- 8.7/9.9 MB 175.8 kB/s eta 0:00:08
   ----------------------------------- ---- 8.7/9.9 MB 175.8 kB/s eta 0:00:08
   ----------------------------------- ---- 8.7/9.9 MB 175.8 kB/s eta 0:00:08
   ----------------------------------- ---- 8.7/9.9 MB 175.8 kB/s eta 0:00:08
   ----------------------------------- ---- 8.7/9.9 MB 175.8 kB/s eta 0:00:08
   ------------------------------------ --- 8.9/9.9 MB 178.2 kB/s eta 0:00:06
   ------------------------------------ --- 8.9/9.9 MB 178.2 kB/s eta 0:00:06
   ------------------------------------ --- 8.9/9.9 MB 178.2 kB/s eta 0:00:06

In [1]:
import pandas as pd
import numpy as np

a={
    'name':['yash','tejas', 'shruti', 'tanish'],
    'marks':[92,88,40,32],
    'city':['itarsi','dabra','betul','katni']
    
}

In [2]:
df=pd.DataFrame(a)
df

     name  marks    city
0    yash     92  itarsi
1   tejas     88   dabra
2  shruti     40   betul
3  tanish     32   katni

In [6]:
import pandas as pd
import numpy as np
#series with custom index
s=pd.Series([10,30,20, 30], index=['a','b','c', 'c'])
print(s)

a    10
b    30
c    20
c    30
dtype: int64

In [3]:
s['b']

np.int64(20)

In [6]:
#creating a series
d={'a': 1, 'b': 2, 'c': 3}
ser=pd.Series(d)
print(ser)

a    1
b    2
c    3
dtype: int64

In [9]:
s.mean()

np.float64(20.0)

In [ ]:
# It finds all different (unique) values in your Pandas Series and removes duplicates.
s.unique()

array([10, 20, 30])

In [7]:
s.value_counts()

30    2
10    1
20    1
Name: count, dtype: int64

In [14]:
a={
    'name':['yash','tejas', 'shruti', 'tanish'],
    'marks':[92,88,40,32],
    'city':['itarsi','dabra','betul','katni']
    
}
df=pd.DataFrame(a)
df

     name  marks    city
0    yash     92  itarsi
1   tejas     88   dabra
2  shruti     40   betul
3  tanish     32   katni

In [20]:
#Shows first 5(by default) rows of the DataFrame.
#You can also give number → df.head(2)
df.head(3)

     name  marks    city
0    yash     92  itarsi
1   tejas     88   dabra
2  shruti     40   betul

In [ ]:
df.tail(3)#last rows

     name  marks   city
1   tejas     88  dabra
2  shruti     40  betul
3  tanish     32  katni

In [ ]:
df.shape#show the number of the rows and coloumn

(4, 3)

In [ ]:
#summary - df.info()
#Statistics - df.describe() 
#Columns list - df.columns

In [25]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    4 non-null      str
 1   marks   4 non-null      int64
 2   city    4 non-null      str
dtypes: int64(1), str(2)
memory usage: 228.0 bytes

In [26]:
df.describe()

          marks
count   4.00000
mean   63.00000
std    31.39002
min    32.00000
25%    38.00000
50%    64.00000
75%    89.00000
max    92.00000

In [8]:
df.columns

Index(['name', 'marks', 'city'], dtype='str')

In [9]:
import pandas as pd
import numpy as np
a={
    'name':['yash','tejas', 'shruti', 'tanish'],
    'marks':[92,88,40,32],
    'city':['itarsi','dabra','betul','katni']
    
}
df=pd.DataFrame(a)
c=df.drop(index=2)#remove rows
print(c)

     name  marks    city
0    yash     92  itarsi
1   tejas     88   dabra
3  tanish     32   katni

In [ ]:
d=df.drop(columns=['city'])#remove coloumns
print(d)

     name  marks
0    yash     92
1   tejas     88
2  shruti     40
3  tanish     32

In [11]:
df.drop(index=3, inplace=True)#This command removes the row whose index is 2 from the DataFrame permanently.
print(df)

     name  marks    city
0    yash     92  itarsi
1   tejas     88   dabra
2  shruti     40   betul

In [1]:
import pandas as pd
import numpy as np
a={
    'name':['yash','tejas', 'shruti', 'tanish'],
    'marks':[92,88,40,32],
    'city':['itarsi','dabra','betul','katni']
    
}
df=pd.DataFrame(a)
df

     name  marks    city
0    yash     92  itarsi
1   tejas     88   dabra
2  shruti     40   betul
3  tanish     32   katni

In [15]:
df.loc[1, 'marks'] = np.nan     # Tejas marks → NaN
df.loc[3, 'city'] = np.nan     # Tanish city → NaN

print(df)

     name  marks    city
0    yash   92.0  itarsi
1   tejas    NaN     NaN
2  shruti   40.0   betul
3  tanish    NaN     NaN

In [14]:
import pandas as pd
import numpy as np
a={
    'name':['yash','tejas', 'shruti', 'tanish'],
    'marks':[92,88,40,32],
    'city':['itarsi','dabra','betul','katni']
    
}
df=pd.DataFrame(a)
df
df.loc[1,'city']=np.nan
df.loc[3,'marks']=np.nan
print(df)

     name  marks    city
0    yash   92.0  itarsi
1   tejas   88.0     NaN
2  shruti   40.0   betul
3  tanish    NaN   katni

In [ ]:
#Removes rows with ANY NaN
df.dropna()

     name  marks    city
0    yash   92.0  itarsi
2  shruti   40.0   betul

In [ ]:
#Removes columns with ANY NaN. Both marks and city have NaN → removed.
df.dropna(axis=1)

     name
0    yash
1   tejas
2  shruti
3  tanish

In [ ]:
df.dropna(how='all')#This removes a row ONLY IF all values in that row are NaN. 
#df.dropna(how='all', axis=1) -> It will remove columns where ALL values are NaN.

     name  marks    city
0    yash   92.0  itarsi
1   tejas   88.0     NaN
2  shruti   40.0   betul
3  tanish    NaN   katni

In [18]:
df.loc[1,'city']=np.nan
df.dropna(thresh=2)#Keeps rows having at least 2 valid values. All rows have ≥2 values → nothing removed.

     name  marks    city
0    yash   92.0  itarsi
2  shruti   40.0   betul

In [19]:
df[['marks', 'city']]
df['name']

0      yash
1     tejas
2    shruti
3    tanish
Name: name, dtype: str

loc works because it is made for label-based selection with conditions.

In [22]:
df.iloc[0:2]

    name  marks    city
0   yash   92.0  itarsi
1  tejas   88.0     NaN

In [13]:
df.loc[0:3]

     name  marks    city
0    yash     92  itarsi
1   tejas     88   dabra
2  shruti     40   betul

| Feature            | `loc`                | `iloc`                 |
| ------------------ | -------------------- | ---------------------- |
| Selection type     | **Label based**      | **Position based**     |
| Uses               | Row/column **names** | Row/column **numbers** |
| End index          | Included             | Excluded               |
| Can use conditions | Yes                  | No                     |

In [23]:
df['age']=[21,22,23,24]
df['salary']=[2500, 3000, 2200, 1500]
print(df)

     name  marks    city  age  salary
0    yash   92.0  itarsi   21    2500
1   tejas   88.0     NaN   22    3000
2  shruti   40.0   betul   23    2200
3  tanish    NaN   katni   24    1500

In [22]:
import pandas as pd
import numpy as np

data = {
    'name': ['yash','tejas','shruti','tanish'],
    'marks': [92, 88, 40, np.nan],
    'city': ['itarsi', np.nan, 'betul', 'katni'],
    'age': [21, 22, 23, 24],
    'salary': [2500, 3000, 2200, 1500]
}

df = pd.DataFrame(data)

print(df)

     name  marks    city  age  salary
0    yash   92.0  itarsi   21    2500
1   tejas   88.0     NaN   22    3000
2  shruti   40.0   betul   23    2200
3  tanish    NaN   katni   24    1500

In [ ]:
#for removing the coloumn u have to write this cmd df.drop(coloumns=[1,-1], axis=1, implace=true)

In [29]:
print(df.drop(df.columns[[1,2]], inplace=True, errors='ignore'))

None

In [30]:
#filtering
f=df[df['age'] < 23]
f

    name  marks    city  age  salary
0   yash   92.0  itarsi   21    2500
1  tejas   88.0     NaN   22    3000

In [31]:
af = df[(df['age'] > 21) & (df['salary'] < 3000)]
af

     name  marks   city  age  salary
2  shruti   40.0  betul   23    2200
3  tanish    NaN  katni   24    1500

**** apply() applies a function to every value of a Series or to each row/column of a DataFrame.

applymap() applies a function to EVERY single cell of the DataFrame.

map() replaces values using a dictionary or function.

apply()

Used to apply a function to each value of a column or row.

applymap()

Used to apply a function to every element of a DataFrame.

map()

Used on Series to replace or transform values.****


???Lambda is an anonymous one-line function in Python used for small, simple operations without defining a full function. like def function

lambda x → take each salary value

x + 1000 → add 1000

apply() → apply to every row???



==apply() works on a column or row, while applymap() works on every element of the DataFrame.==

In [ ]:
df['salary']=df['salary'].apply(lambda x : x+1000)# APPLY->applies a function to every value of a Series or to each row/column of a DataFrame.
df

     name  marks    city  age  salary
0    yash   92.0  itarsi   21    3500
1   tejas   88.0     NaN   22    4000
2  shruti   40.0   betul   23    3200
3  tanish    NaN   katni   24    2500

In [47]:
df[['marks','age','salary']] = df[['marks','age','salary']].apply(lambda col: col*2)
df

     name  marks    city  age  salary
0    yash  368.0  itarsi   84   14000
1   tejas  352.0     NaN   88   16000
2  shruti  160.0   betul   92   12800
3  tanish    NaN   katni   96   10000

applymap cmd ask with someone expert in pandas

In [ ]:
df['name']=df['name'].map(lambda x: x.upper()) #map use for replacing and tranforming the values
df

     name  marks    city  age  salary
0    YASH  368.0  itarsi   84   14000
1   TEJAS  352.0     NaN   88   16000
2  SHRUTI  160.0   betul   92   12800
3  TANISH    NaN   katni   96   10000

In [50]:
city_map={
    'itarsi':'et',
    'dabra':'dba',
    'betul':'bzu',
    'katni': 'kte'

}
df['city']=df['city'].map(city_map)
df

     name  marks city  age  salary
0    YASH  368.0   et   84   14000
1   TEJAS  352.0  NaN   88   16000
2  SHRUTI  160.0  bzu   92   12800
3  TANISH    NaN  kte   96   10000

In [33]:
#adding new rows
new_rows = pd.DataFrame([
    {'name':'lavanya', 'marks':85, 'city':'bhopal', 'age':22, 'salary':2600},
    {'name':'pranjal', 'marks':78, 'city':'indore', 'age':23, 'salary':2400}
])

df = pd.concat([df, new_rows], ignore_index=True)

print(df)

      name  marks    city  age  salary
0     yash   92.0  itarsi   21    2500
1    tejas   88.0     NaN   22    3000
2   shruti   40.0   betul   23    2200
3   tanish    NaN   katni   24    1500
4  lavanya   85.0  bhopal   22    2600
5  pranjal   78.0  indore   23    2400
6  lavanya   85.0  bhopal   22    2600
7  pranjal   78.0  indore   23    2400

In [34]:
import pandas as pd
import numpy as np

data = {
    'name': ['yash','tejas','shruti','tanish','lavanya','pranjal'],
    'marks': [92, 88, 40, 45, 86, 76],
    'city': ['itarsi', 'dabra', 'betul', 'katni','gwalior', 'morena'],
    'age': [21, 24, 22, 19, 18, 20],
    'salary': [2500, 3000, 2200, 1500, 4000, 1700]
}

df = pd.DataFrame(data)
df

      name  marks     city  age  salary
0     yash     92   itarsi   21    2500
1    tejas     88    dabra   24    3000
2   shruti     40    betul   22    2200
3   tanish     45    katni   19    1500
4  lavanya     86  gwalior   18    4000
5  pranjal     76   morena   20    1700

age → small to large (ascending = True)

salary → large to small (ascending = False)


for descending

df.sort_values(by=['age','salary'], ascending=[False, False])

In [ ]:

e=df.sort_values(by=['age','salary'], ascending=[True, False])# sorting we can use by= or without by=. for multiple values use by=
e

      name  marks     city  age  salary
4  lavanya     86  gwalior   18    4000
3   tanish     45    katni   19    1500
5  pranjal     76   morena   20    1700
0     yash     92   itarsi   21    2500
2   shruti     40    betul   22    2200
1    tejas     88    dabra   24    3000

In [64]:
b=df.sort_values("salary")
b

      name  marks     city  age  salary
3   tanish     45    katni   19    1500
5  pranjal     76   morena   20    1700
2   shruti     40    betul   22    2200
0     yash     92   itarsi   21    2500
1    tejas     88    dabra   24    3000
4  lavanya     86  gwalior   18    4000

In [35]:
df.sort_values(by=['age','salary'], ascending=[False, False])

      name  marks     city  age  salary
1    tejas     88    dabra   24    3000
2   shruti     40    betul   22    2200
0     yash     92   itarsi   21    2500
5  pranjal     76   morena   20    1700
3   tanish     45    katni   19    1500
4  lavanya     86  gwalior   18    4000

rank() assigns ranking numbers to values of a column. By default, lowest value gets rank 1.
tanish → 1.0  (lowest salary)
pranjal → 2.0
shruti → 3.0
yash → 4.0
tejas → 5.0
lavanya → 6.0 (highest salary)

In [36]:
import pandas as pd
import numpy as np

data = {
    'name': ['yash','tejas','shruti','tanish','lavanya','pranjal'],
    'marks': [92, 88, 40, 45, 86, 76],
    'city': ['itarsi', 'dabra', 'betul', 'katni','gwalior', 'morena'],
    'age': [21, 24, 22, 19, 18, 20],
    'salary': [2500, 3000, 2200, 1500, 4000, 1700]
}

df = pd.DataFrame(data)
df

      name  marks     city  age  salary
0     yash     92   itarsi   21    2500
1    tejas     88    dabra   24    3000
2   shruti     40    betul   22    2200
3   tanish     45    katni   19    1500
4  lavanya     86  gwalior   18    4000
5  pranjal     76   morena   20    1700

In [71]:
df['rank']=df['salary'].rank()
df

      name  marks     city  age  salary  rank
0     yash     92   itarsi   21    2500   4.0
1    tejas     88    dabra   24    3000   5.0
2   shruti     40    betul   22    2200   3.0
3   tanish     45    katni   19    1500   1.0
4  lavanya     86  gwalior   18    4000   6.0
5  pranjal     76   morena   20    1700   2.0

| Name    | Salary | Rank |
| ------- | ------ | ---- |
| lavanya | 4000   | 1    |
| tejas   | 3000   | 2    |
| yash    | 2500   | 3    |
| shruti  | 2200   | 4    |
| pranjal | 1700   | 5    |
| tanish  | 1500   | 6    |

In [72]:
df['rank']=df['salary'].rank(ascending=False)
df

      name  marks     city  age  salary  rank
0     yash     92   itarsi   21    2500   3.0
1    tejas     88    dabra   24    3000   2.0
2   shruti     40    betul   22    2200   4.0
3   tanish     45    katni   19    1500   6.0
4  lavanya     86  gwalior   18    4000   1.0
5  pranjal     76   morena   20    1700   5.0

df['Age'].mean()
df['Age'].median()
df['Age'].std()
df['Age'].var()
df['Age'].min()
df['Age'].max()
df['Age'].sum()

In [ ]:
df['age'].mean()

np.float64(20.666666666666668)

Positive skew → tail on right
Negative skew → tail on left

In [74]:
#skewness
df['salary'].skew()

np.float64(0.8380522860462541)

kurtosis
High kurtosis → heavy tails (outliers)
Low kurtosis → light tails

In [75]:
df['salary'].kurt()

np.float64(0.28894086091086546)

In [76]:
#MEMBERSHIP TEST checks whether each value in a column exists in the given list and returns True/False.
df['name'].isin(['alice', 'yash'])

0     True
1    False
2    False
3    False
4    False
5    False
Name: name, dtype: bool

In [77]:
'alice' in df['name'].values

False

In [78]:
df['job']=['engineer','analyst','ips','smith','developer','lawyer']
df

      name  marks     city  age  salary  rank        job
0     yash     92   itarsi   21    2500   3.0   engineer
1    tejas     88    dabra   24    3000   2.0    analyst
2   shruti     40    betul   22    2200   4.0        ips
3   tanish     45    katni   19    1500   6.0      smith
4  lavanya     86  gwalior   18    4000   1.0  developer
5  pranjal     76   morena   20    1700   5.0     lawyer

In [38]:
new_row=pd.DataFrame([{'name':'pushpi','marks':68,'age':30,'salary':2400,'rank':7.0,'job':'appdev'}])
df=pd.concat([df,new_row], ignore_index=True)
df

      name  marks     city  age  salary  rank     job
0     yash     92   itarsi   21    2500   NaN     NaN
1    tejas     88    dabra   24    3000   NaN     NaN
2   shruti     40    betul   22    2200   NaN     NaN
3   tanish     45    katni   19    1500   NaN     NaN
4  lavanya     86  gwalior   18    4000   NaN     NaN
5  pranjal     76   morena   20    1700   NaN     NaN
6   pushpi     68      NaN   30    2400   7.0  appdev
7   pushpi     68      NaN   30    2400   7.0  appdev

In [5]:
import pandas as pd 
import numpy as np
df=pd.DataFrame(np.arange(0,16).reshape(4,4),index=['row1','row2','row3','row4'],columns=['col1','col2','col3','col4'])
print(df)

      col1  col2  col3  col4
row1     0     1     2     3
row2     4     5     6     7
row3     8     9    10    11
row4    12    13    14    15

In [6]:
#accesing the element
df.loc['row1']

col1    0
col2    1
col3    2
col4    3
Name: row1, dtype: int64

In [9]:
df.iloc[2:,:3]

      col1  col2  col3
row3     8     9    10
row4    12    13    14

In [11]:
#convert dataframe into array
df.iloc[1:,1:].values

array([[ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])